version: '3.7'
services:
  backend-node:
    container_name: backend-node
    build: 
      context: ./backend-nodejs
      dockerfile: ./Dockerfile
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://damian:password@mongo:27017/mongo_db?authSource=admin
      - JWT_SECRET=supersecretpassword
      - PAYPAL_CLIENT_ID=paypal_id
      - cloud_name=clodinary_cloud_name
      - api_key=clodinary_api_key
      - api_secret=clodinary_api_secret
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: damian
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongo
  react-frontend:
    container_name: react-frontend
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend-node


volumes:
  mongo-data:
